name: Release NPM

on:
  push:
    tags: [ v* ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v}" >> $GITHUB_OUTPUT
      - name: Run Npm Scripts
        run: |
          node -v
          npm -v
          npm install
          node -e 'var pkg = require("./package.json"); pkg.version= "${{ steps.get_version.outputs.VERSION }}"; require("fs").writeFileSync("./package.json", JSON.stringify(pkg, null, 2))'
          npm run build
          cd lib
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUNT_NPM_TOKEN }}